# This workflow will install Python dependencies, run tests and lint with a variety of Python versions!
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI with Xray server/DC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Export scenarios from Xray and generate .feature file(s)
      run: |
        FEATURES_FILE=features.zip
        rm -f $FEATURES_FILE
        curl -u ${{ secrets.JIRASERVER_USERNAME }}:${{ secrets.JIRASERVER_PASSWORD }}  "${{ secrets.JIRASERVER_BASE_URL }}/rest/raven/2.0/export/test?keys=${{ secrets.XRAYSERVER_ISSUE_KEYS_TO_EXPORT_FROM }}&fz=true" -o $FEATURES_FILE
        rm -f features/*.feature
        unzip -o $FEATURES_FILE  -d features
    - name: Run test scenarios with behave
      run: |
        export PYTHONPATH=.
        behave --format=cucumber_json126:PrettyCucumberJSONFormatter -o results/cucumber.json  --format=json -o results/behave.json features
    - name: "Import results to Xray server/DC using GH Action (disabled)"
      if: ${{ false }}
      uses: mikepenz/xray-action@v1.1.0
      with:
         username: ${{ secrets.JIRA_USERNAME }}
         password: ${{ secrets.JIRA_PASSWORD }}
         xrayCloud: "false"
         xrayBaseUrl: ${{ secrets.JIRA_BASEURL }}
         testFormat: "cucumber"
         testPaths: "**/results/cucumber.json"
         projectKey: "XT"
    - name: generate auxiliary file to define fields on the Test Execution
      run: |
        cat testexec_template.json  | sed s/PROJECT_KEY/${{ secrets.JIRASERVER_PROJECT_KEY }}/g | sed s/CF_TEST_ENVIRONMENT/${{ secrets.JIRASERVER_CF_TEST_ENVIRONMENTS }}/g |  sed s/TEST_ENVIRONMENT_NAME/${{ env.BROWSER }}/g | sed s/CF_TEST_PLAN/${{ secrets.JIRASERVER_CF_TEST_PLAN }}/g  | sed s/TESTPLAN_KEY/${{ secrets.XRAYSERVER_TEST_PLAN_KEY }}/g > test_exec.json
    - name: "Import results to Xray (server/DC) using multipart endpoint"
      run: |
        curl -X POST -u ${{ secrets.JIRASERVER_USERNAME }}:${{ secrets.JIRASERVER_PASSWORD }} -F info=@test_exec.json -F result=@"results/cucumber.json" ${{ secrets.JIRASERVER_BASE_URL }}/rest/raven/2.0/import/execution/cucumber/multipart
